version: '3.1'

services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: domace
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
        networks:
            - monitoring
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3000:3000"
        networks:
            - monitoring

networks:
    monitoring:
        driver: bridge

volumes:
    prometheus-data:
